image: docker:git

# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_REGISTRY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:20.10.16-dind

before_script:
  - until docker info; do sleep 1; done

stages:
  - build
  # - test
  # - deploy

build-rocky:
  image: rockylinux:9
  stage: build
  tags:
    - amd64
  before_script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install -y docker-ce docker-ce-cli containerd.io packer make git
  script:
    - docker login -u monofuel -p $DOCKER_TOKEN
    - docker context create gitlab
    - docker buildx create --name builder --use gitlab --bootstrap --config ./buildkitd.toml
    - make build-rocky9
    - make build-rocky8

build-alpine:
  image: rockylinux:9
  stage: build
  tags:
    - amd64
  before_script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install -y docker-ce docker-ce-cli containerd.io packer make git
  script:
    - docker login -u monofuel -p $DOCKER_TOKEN
    - docker context create gitlab
    - docker buildx create --name builder --use gitlab --bootstrap --config ./buildkitd.toml
    - make build-alpine

build-ubuntu:
  image: rockylinux:9
  stage: build
  tags:
    - amd64
  before_script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install -y docker-ce docker-ce-cli containerd.io packer make git
  script:
    - docker login -u monofuel -p $DOCKER_TOKEN
    - docker context create gitlab
    - docker buildx create --name builder --use gitlab --bootstrap --config ./buildkitd.toml
    - make build-ubuntu22
    - make build-ubuntu20
# TODO test
# perhaps build image, push to gitlab registry, then pull and test, and then push to dockerhub?

# test:
#   stage: test
#   tags:
#     - amd64
#   script:
#     - docker run monofuel/nim "bash -c 'cd /opt/Nim && ./koch tests'"

# deploy:
#   stage: deploy
#   tags:
#     - amd64
#   script:
#     - docker push monofuel/nim:amd64
#   only:
#     - master
