image: docker:git

# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_REGISTRY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:20.10.16-dind

before_script:
  - until docker info; do sleep 1; done

stages:
  - build
  # - test
  - deploy

build-builder:
  image: registry.gitlab.com/mono-homelab/nim-docker:builder
  stage: build
  tags:
    - amd64
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    - make pull-builder
    - make build-builder

deploy-rocky:
  image: registry.gitlab.com/mono-homelab/nim-docker:builder
  stage: deploy
  tags:
    - amd64
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    - make pull-rocky9
    - make pull-rocky8
    - docker login -u monofuel -p $DOCKER_TOKEN
    - docker context create gitlab
    - docker buildx create --name builder --use gitlab --bootstrap --config ./buildkitd.toml
    - make build-rocky9
    - make build-rocky8

deploy-alpine:
  image: registry.gitlab.com/mono-homelab/nim-docker:builder
  stage: deploy
  tags:
    - amd64
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    - make pull-alpine
    - docker login -u monofuel -p $DOCKER_TOKEN
    - docker context create gitlab
    - docker buildx create --name builder --use gitlab --bootstrap --config ./buildkitd.toml
    - make build-alpine

deploy-ubuntu:
  image: registry.gitlab.com/mono-homelab/nim-docker:builder
  stage: deploy
  tags:
    - amd64
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    - make pull-ubuntu22
    - make pull-ubuntu20
    - docker login -u monofuel -p $DOCKER_TOKEN
    - docker context create gitlab
    - docker buildx create --name builder --use gitlab --bootstrap --config ./buildkitd.toml
    - make build-ubuntu22
    - make build-ubuntu20
# TODO test
# perhaps build image, push to gitlab registry, then pull and test, and then push to dockerhub?

# test:
#   stage: test
#   tags:
#     - amd64
#   script:
#     - docker run monofuel/nim "bash -c 'cd /opt/Nim && ./koch tests'"

# deploy:
#   stage: deploy
#   tags:
#     - amd64
#   script:
#     - docker push monofuel/nim:amd64
#   only:
#     - master
