before_script:
  - docker info

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
     - docker build --no-cache -t monofuel/nim:amd64 .

test:
  stage: test
  script:
    - echo skipping tests (need more deps and junk)
    #- docker run monofuel/nim:amd64 cd /opt/Nim && ./koch tests

deploy:
  stage: deploy
  script:
    - docker push monofuel/nim:amd64
  only:
  - master