image: docker:git

# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_REGISTRY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

services:
  - docker:20.10.16-dind

before_script:
  - until docker info; do sleep 1; done

stages:
  - build
  # - test
  # - deploy

build:
  image: rockylinux:9
  stage: build
  tags:
    - amd64
  before_script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    - yum install -y docker packer make
  script:
    - echo "$DOCKER-TOKEN" | docker login -u monofuel --password-stdin
    - make buildx # TODO move to packer
    - make packer-init
    - make packer-build
# TODO test
# perhaps build image, push to gitlab registry, then pull and test, and then push to dockerhub?

# test:
#   stage: test
#   tags:
#     - amd64
#   script:
#     - docker run monofuel/nim "bash -c 'cd /opt/Nim && ./koch tests'"

# deploy:
#   stage: deploy
#   tags:
#     - amd64
#   script:
#     - docker push monofuel/nim:amd64
#   only:
#     - master
