FROM ubuntu:22.04

RUN apt update && apt install -y git gcc gcc-c++ make which && apt clean

# install nim and perform cleanup in one layer
COPY ./setup.sh /root/
RUN sh /root/setup.sh
ENV PATH="/root/.nimble/bin:${PATH}"