FROM rockylinux:9

RUN yum install -y git gcc gcc-c++ make which

# install nim and perform cleanup in one layer
COPY ./setup.sh /root/
RUN sh /root/setup.sh
ENV PATH="/opt/Nim/bin/:/root/.nimble/bin:${PATH}"