- hosts:
    - nim
  tasks:
    - name: install git
      ansible.builtin.package:
        name:
          - git
          - which
          - make
          - gcc
          - gcc-c++
        state: present
    - name: clone nim to /opt/Nim
      git:
        repo: https://github.com/nim-lang/Nim.git
        dest: /opt/Nim
        recursive: yes
        depth: 1
    - name: run build_all.sh
      shell: sh ./build_all.sh
      args:
        chdir: /opt/Nim
    - name: build koch
      shell: ./bin/nim c koch
      args:
        chdir: /opt/Nim
    - name: koch boot
      shell: ./koch boot -d:release
      args:
        chdir: /opt/Nim
    - name: koch tools
      shell: ./koch tools
      args:
        chdir: /opt/Nim
    - name: delete sources
      file:
        path: /opt/Nim
        state: absent
        force: yes
